name: dev_compiler
# When updating this version, also update the version in lib/devc.dart.
version: 0.1.18
description: >
  Experimental Dart to JavaScript compiler designed to create idiomatic,
  readable JavaScript output.

author: Dart Dev Compiler team <dev-compiler@dartlang.org>
homepage: https://github.com/dart-lang/dev_compiler

dependencies:
  analyzer: ^0.27.2-alpha.1
  barback: ^0.15.2+7
  code_transformers: ^0.4.0
  args: ^0.13.0
  cli_util: ^0.0.1
  crypto: ^0.9.0
  html: ^0.12.0
  js: ">=0.6.0 <0.7.0"
  logging: ">=0.9.2 <0.12.0"
  path: ^1.3.0
  pub_semver: ^1.1.0
  shelf: ">=0.5.6 <0.7.0"
  shelf_static: ^0.2.1
  source_maps: ^0.10.0
  source_span: ^1.0.2
  yaml: ^2.1.2

dev_dependencies:
  # We pin a specific version to ensure everyone is formatting the code exactly
  # the same way. This is because any change in dart_style, even non-breaking
  # changes, may change the output format.
  dart_style: 0.2.2
  test: ^0.12.0
  transformer_test: ^0.1.0
  webdriver: ^0.8.8

environment:
  sdk: ">=1.12.0 <2.0.0"

executables:
  # Similar to "analyzer.dart" and its command line "dartanalyzer" we use
  # "dartdevc".
  dartdevc: dartdevc
  dev_compiler:
  # Similar to dartdevc, but runs the (single) entry point with iojs (requires
  # a very recent iojs next-nightly version).
  dartdevrun: devrun
